### ISSUE TITLE
the comments implementation is currently bananas

### ISSUE THREAD

**Issue by andriibeee** [kheina-com/backend#1]

**Comment by kheina** [comment]
there are many things I want to fix but what is this in reference to specifically

**Comment by andriibeee** [comment]
also not sure if this is a feature but comments popping up on the index page looks off like in 'it's probs not how it should behave'

**Comment by kheina** [comment]
yeah I should have fixed the 500s, I recently changed db libraries which caused that. but ye once people actually use the site and vote n shit I didn't think comments will appear much/at all on the home page
